CREATE DATABASE CollegeWebSite;
GO;

USE CollegeWebSite;
GO;

CREATE TABLE Users (
	Id int IDENTITY(1,1) PRIMARY KEY,
	UserName nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Password nvarchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);
 CREATE  UNIQUE NONCLUSTERED INDEX IX_Users_UserName ON dbo.Users (  UserName ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO;
